name: Deploy

on:
  push:
    branches:
      - master

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2 
      - uses: actions/setup-node@v2
        with:
          node-version: '16.14.0'

      - name: Setup bot
        env:
          bot_username: '${{ secrets.BOT_USERNAME }}'
          bot_email: '${{ secrets.BOT_EMAIL }}'
          bot_access_token: '${{ secrets.BOT_ACCESS_TOKEN }}'
        run: |
          git config --global credential.helper store
          echo "https://${bot_access_token}:x-oauth-basic@github.com" > ~/.git-credentials
          git config --global user.email $bot_email
          git config --global user.name $bot_username

      - name: Install dependencies
        run: yarn install

      - name: Deploy to gh-pages
        run: |
          yarn build  # Gera o build do projeto
          cd build
          git init  # Inicializa um repositório Git
          git add -A  # Adiciona todos os arquivos
          git commit -m "🚀 Deploy id ${GITHUB_RUN_ID}"  # Faz o commit com o GITHUB_RUN_ID
          git push -f https://${bot_access_token}:x-oauth-basic@github.com/elevatte/elevatte.github.io.git gh-pages  # Faz o push forçado para a branch gh-pages
